#!/bin/bash -e

TMP_DIR="/tmp/mthemedaemon-stresstest.tmp"

export LD_LIBRARY_PATH="$(dirname $0):${LD_LIBRARY_PATH}"

rm -rf ${TMP_DIR}
cp -r $(dirname $0)/data/stresstest ${TMP_DIR}
cd ${TMP_DIR}
exec $0.bin "${@}"
